"""SCL for the generated step sequencer.

One FB per machine, holding a single CASE over the step number. Each branch holds
the device requests for that step, the transition that leaves it, its timeout and
its identity - so the whole sequence reads top to bottom in step order, which is
how somebody debugging it will read it.

Three things are published that a hand-written sequencer usually lacks, because
the generator knows them and a person would forget one:

  Step         which step is active
  BlockedById  which condition is holding it, as a text-list index
  StepTime     how long it has been holding, with a per-step maximum

The conditions themselves are not read here. The machine FB fills a Cond struct
and passes it in, so this block contains no device knowledge and the mapping from
"Lift.Opened" to a DevIf member stays in exactly one visible place.
"""

from __future__ import annotations

from typing import List

from . import sequence as seq_mod
from .model import Spec
from .sequence import Sequence

HEADER = (
    "// Generated by tiagen - do not edit.\n"
    "// Edit the spec's sequence section and rebuild.\n"
)

_ON_TIMEOUT_CODE = {"fault": 0, "continue": 2, "hold": 1}


def _q(name: str) -> str:
    return f'"{name}"'


def emit_udt_cond(spec: Spec, seq: Sequence) -> str:
    """One Bool per distinct wait condition, filled by the machine FB."""
    from .emit_scl import _struct

    conditions = seq_mod.conditions_of(spec, seq)
    members = [
        (c.key, "Bool", f"{c.source}")
        for c in conditions
    ]
    return _struct(
        spec.udt_cond,
        members,
        "Resolved step conditions. The machine FB evaluates each one from the device\n"
        "instances and passes this struct to the sequencer, so the sequencer holds no\n"
        "device knowledge and every condition is mapped in one reviewable place.",
    )


def emit_fb_sequence(spec: Spec, seq: Sequence) -> str:
    # Blocked-reason ids distinguish a condition from its negation; the Cond struct
    # does not, because one bit serves both.
    reason_id = {
        (c.key, c.negated): index
        for index, c in enumerate(seq_mod.reasons_of(spec, seq), start=1)
    }
    steps = seq.steps

    lines: List[str] = [HEADER, f"FUNCTION_BLOCK {_q(spec.fb_sequence)}"]
    lines += [
        "{ S7_Optimized_Access := 'TRUE' }",
        "VERSION : 0.1",
        "   VAR_INPUT",
        "      AutoRun : Bool;                    // sequence may advance",
        "      Reset : Bool;                      // clear a latched timeout and the maxima",
        "      Hold : Bool;                       // freeze on the active step",
        f"      Cond : {_q(spec.udt_cond)};",
        "   END_VAR",
        "",
        "   VAR_OUTPUT",
        f"      Step : Int;                        // active step, {seq.idle_number} when idle",
        "      BlockedById : Int;                 // condition holding the step, 0 = none",
        "      StepTime : Time;                   // time on the active step",
        "      Timeout : Bool;                    // latched: a step exceeded its timeout",
        "      Complete : Bool;                   // one cycle when the last step finishes",
        "   END_VAR",
        "",
        "   VAR_IN_OUT",
        f"      Auto : {_q(spec.udt_auto)};            // device requests",
        "   END_VAR",
        "",
        "   VAR",
        "      StepTimer : TON_TIME;",
        "      Prev : Int;                        // step number last cycle, to reset the timer",
        "      TimeoutLatch : Bool;",
        f"      StepTimeMax : Array[0..{len(steps) - 1}] of Time;   // longest time per step, since Reset",
        "   END_VAR",
        "",
        "   VAR_TEMP",
        "      vNext : Int;",
        "      vIdx : Int;",
        "      vPt : Time;",
        "      vOnTimeout : Int;",
        "      vAdvance : Bool;",
        "      vBlocked : Int;",
        "      vIsLast : Bool;",
        "      vActive : Bool;",
        "      i : Int;",
        "   END_VAR",
        "",
        "BEGIN",
    ]

    # ---- entry and exit ---------------------------------------------------
    lines += [
        "    // ==================================================================",
        "    // 1. Entry and exit. Losing AutoRun returns to idle; the machine FB",
        "    //    clears the Auto requests in the same cycle, so nothing is left",
        "    //    energised by a sequence that stopped.",
        "    // ==================================================================",
        "    IF #Reset THEN",
        "        #TimeoutLatch := FALSE;",
        f"        FOR #i := 0 TO {len(steps) - 1} DO",
        "            #StepTimeMax[#i] := T#0MS;",
        "        END_FOR;",
        "    END_IF;",
        "",
        "    IF NOT #AutoRun THEN",
        f"        #Step := {seq.idle_number};",
        "        #TimeoutLatch := FALSE;",
        f"    ELSIF #Step = {seq.idle_number} THEN",
        f"        #Step := {steps[0].number};        // {steps[0].name}",
        "    END_IF;",
        "",
        "    #vAdvance := FALSE;",
        "    #vBlocked := 0;",
        "    #vIsLast := FALSE;",
        "    #vIdx := 0;",
        "    #vPt := T#0MS;",
        "    #vOnTimeout := 0;",
        f"    #vNext := {seq.idle_number};",
        "    #Complete := FALSE;",
        "",
    ]

    # ---- the sequence -----------------------------------------------------
    lines += [
        "    // ==================================================================",
        "    // 2. The sequence. One branch per step: requests, then the transition.",
        "    //    Requests are re-asserted every cycle the step is active, so a",
        "    //    request never outlives its step.",
        "    // ==================================================================",
        "    CASE #Step OF",
    ]
    for index, step in enumerate(steps):
        lines += _step_branch(spec, seq, step, index, reason_id)
    lines += [
        "        ELSE",
        "            ;   // idle, or a step number nothing sets",
        "    END_CASE;",
        "",
    ]

    # ---- timing -----------------------------------------------------------
    lines += [
        "    // ==================================================================",
        "    // 3. Step timing. The timer resets on the cycle the step number",
        "    //    changes, which costs one cycle of resolution and needs no",
        "    //    per-step timer instance.",
        "    // ==================================================================",
        f"    #vActive := #AutoRun AND #Step <> {seq.idle_number} AND NOT #Hold;",
        "    #StepTimer(IN := #vActive AND #Step = #Prev,",
        "               PT := #vPt);",
        "    #StepTime := #StepTimer.ET;",
        "    #Prev := #Step;",
        "",
        "    IF #StepTime > #StepTimeMax[#vIdx] THEN",
        "        #StepTimeMax[#vIdx] := #StepTime;",
        "    END_IF;",
        "",
        "    // A step with no timeout has PT = 0, and TON never sets Q for PT = 0.",
        "    IF #vPt > T#0MS AND #StepTimer.Q THEN",
        "        CASE #vOnTimeout OF",
        "            0:",
        "                #TimeoutLatch := TRUE;      // fault: hold until Reset",
        "            2:",
        "                #vAdvance := TRUE;          // continue: treat the timeout as the transition",
        "            ELSE",
        "                ;                           // hold: wait, without faulting",
        "        END_CASE;",
        "    END_IF;",
        "    #Timeout := #TimeoutLatch;",
        "",
        "    // ==================================================================",
        "    // 4. Advance. A latched timeout or Hold freezes the step, so the",
        "    //    requests above keep asserting and nothing half-completes.",
        "    // ==================================================================",
        "    IF #TimeoutLatch OR #Hold THEN",
        "        #vAdvance := FALSE;",
        "    END_IF;",
        "",
        "    IF #vAdvance THEN",
        "        #Step := #vNext;",
        "        #Complete := #vIsLast;",
        "    END_IF;",
        "",
        "    #BlockedById := #vBlocked;",
        "END_FUNCTION_BLOCK",
    ]
    return "\n".join(lines) + "\n"


def _step_branch(spec: Spec, seq: Sequence, step, index: int, reason_id) -> List[str]:
    pad = "            "
    successor = seq.successor(step)
    lines = [
        f"        {step.number}:",
        f"{pad}// ---- {step.number} {step.name} ----",
        f"{pad}// {step.message}",
        f"{pad}#vIdx := {index};",
    ]

    if step.actions:
        for text in step.actions:
            action = seq_mod.resolve_action(spec, text)
            lines.append(f"{pad}#Auto.{action.member} := {action.value};   // {action.source}")
    else:
        lines.append(f"{pad};   // no requests: this step only waits")

    if step.timeout_ms:
        lines.append(f"{pad}#vPt := {seq_mod.scl_time(step.timeout_ms)};")
        lines.append(f"{pad}#vOnTimeout := {_ON_TIMEOUT_CODE[step.on_timeout]};   // on_timeout: {step.on_timeout}")

    lines.append(f"{pad}#vNext := {successor if successor is not None else seq.idle_number};")
    if step is seq.steps[-1]:
        lines.append(f"{pad}#vIsLast := TRUE;")

    lines += _transition(spec, step, reason_id, pad)
    lines.append("")
    return lines


def _transition(spec: Spec, step, reason_id, pad: str) -> List[str]:
    if not step.wait_for:
        return [f"{pad}#vAdvance := TRUE;   // unconditional: advances the cycle after entry"]

    resolved = [seq_mod.resolve_condition(spec, t) for t in step.wait_for]
    terms = [
        f"NOT #Cond.{c.key}" if c.negated else f"#Cond.{c.key}"
        for c in resolved
    ]
    joiner = " AND " if step.wait_mode == "all" else " OR "
    lines: List[str] = []

    if len(terms) == 1:
        lines.append(f"{pad}IF {terms[0]} THEN")
    else:
        indent = pad + " " * 3
        joined = (joiner.rstrip() + "\n" + indent).join(terms)
        lines.append(f"{pad}IF {joined} THEN")
    lines.append(f"{pad}    #vAdvance := TRUE;")

    # Report the *first* unsatisfied condition - the vBlocked = 0 guard is what
    # makes it the first rather than the last. For an "any" step every term is
    # false when we get here, so the first one is as good an answer as exists.
    if step.wait_mode == "all" and len(resolved) > 1:
        lines.append(f"{pad}ELSE")
        for cond, term in zip(resolved, terms):
            reason = reason_id[(cond.key, cond.negated)]
            lines.append(f"{pad}    IF #vBlocked = 0 AND NOT ({term}) THEN")
            lines.append(f"{pad}        #vBlocked := {reason};   // {cond.source}")
            lines.append(f"{pad}    END_IF;")
    else:
        first = resolved[0]
        lines.append(f"{pad}ELSE")
        lines.append(
            f"{pad}    #vBlocked := {reason_id[(first.key, first.negated)]};"
            f"   // {first.source}"
        )
    lines.append(f"{pad}END_IF;")
    return lines


# --------------------------------------------------------------------------
# The machine FB's half: fill Cond, call the sequencer
# --------------------------------------------------------------------------
def machine_call(spec: Spec, seq: Sequence) -> List[str]:
    """Lines the machine FB uses to evaluate conditions and run the sequencer."""
    conditions = seq_mod.conditions_of(spec, seq)
    lines = [
        "    // ==================================================================",
        "    // 3a. Step conditions. Every condition the sequence waits on, read",
        "    //     from the device instances. This is the only place a status",
        "    //     name in the spec becomes a DevIf member.",
        "    // ==================================================================",
    ]
    width = max((len(c.key) for c in conditions), default=1)
    for cond in conditions:
        pad = " " * (width - len(cond.key))
        lines.append(f"    #Cond.{cond.key}{pad} := {cond.expression};")
    if not conditions:
        lines.append("    ;   // the sequence waits on nothing")
    lines += [
        "",
        "    // ==================================================================",
        "    // 3b. The generated step sequence.",
        "    // ==================================================================",
        "    // Hold reads last cycle's fault state, because alarms are aggregated in",
        "    // section 5. One cycle late to stop advancing is harmless - the device FBs",
        "    // have already dropped their outputs via Enable. AnyFault already includes",
        "    // the safety status, so it is the only term needed here.",
        "    #Seq(AutoRun := #AutoRun,",
        "         Reset := #vReset,",
        "         Hold := #AnyFault,",
        "         Cond := #Cond,",
        "         Auto := #Auto);",
        "",
    ]
    return lines


# --------------------------------------------------------------------------
# HMI text lists
# --------------------------------------------------------------------------
def text_lists(spec: Spec, seq: Sequence) -> List[dict]:
    """Step messages and blocked reasons, as text lists.

    A Unified Basic panel has no scripting, so a message cannot be assembled at
    runtime. Both lists are therefore indexed by a value the PLC publishes, and a
    symbolic I/O field resolves the text - configuration only, no script.
    """
    steps = [
        {"value": seq.idle_number, "text": "Idle - auto not running"},
    ] + [
        {"value": s.number, "text": s.message} for s in seq.steps
    ]

    reasons = [{"value": 0, "text": "Not waiting"}]
    for index, cond in enumerate(seq_mod.reasons_of(spec, seq), start=1):
        reasons.append({"value": index, "text": _reason_text(spec, cond)})

    return [
        {
            "name": f"{seq.name}_StepMessage",
            "selection": "value",
            "tag": f"{spec.db_machine}.Seq.Step",
            "comment": "Step message, indexed by the active step number",
            "entries": steps,
        },
        {
            "name": f"{seq.name}_BlockedBy",
            "selection": "value",
            "tag": f"{spec.db_machine}.Seq.BlockedById",
            "comment": "Why the active step is not advancing",
            "entries": reasons,
        },
    ]


def _reason_text(spec: Spec, cond) -> str:
    """Phrase a condition as the thing the machine is waiting for.

    A negated condition is phrased "to clear" rather than printed with a NOT: the
    person reading this is looking at a 7-inch panel, not a listing.
    """
    words = cond.source.strip().split()
    subject = words[1] if words[0].lower() == "not" else words[0]
    device_name = subject.split(".")[0]

    description = None
    for eq in spec.equipment:
        if eq.name == device_name:
            description = eq.description
            break

    what = subject if not cond.negated else subject
    phrase = f"Waiting for {what} to clear" if cond.negated else f"Waiting for {what}"
    if len(words) == 3:      # a comparison: keep the operator and the number
        phrase = f"Waiting for {' '.join(words[-3:])}"
    return f"{phrase} ({description})" if description else phrase
