"""Emitters for the machine-specific SCL: interface UDTs, the machine FB and OB1."""

from __future__ import annotations

from typing import Dict, List

from . import devices as dev
from .model import Equipment, Spec

HEADER = "// Generated by tiagen - edit the machine spec, not this file.\n"

# Auto-mode request members contributed by each equipment type.
AUTO_MEMBERS = {
    "motor_dol": [("_Start", "Bool", "auto start request"), ("_Stop", "Bool", "auto stop request")],
    "motor_reversing": [("_Fwd", "Bool", "auto forward request"), ("_Rev", "Bool", "auto reverse request")],
    "vfd_analog": [
        ("_Start", "Bool", "auto start request"),
        ("_Stop", "Bool", "auto stop request"),
        ("_Speed", "Real", "auto speed setpoint"),
    ],
    "valve_single": [("_Open", "Bool", "auto open request")],
    "valve_double": [("_Open", "Bool", "auto open request")],
    "digital_output": [("_Cmd", "Bool", "auto command")],
    "analog_output": [("_Value", "Real", "auto setpoint")],
}


def _q(name: str) -> str:
    return f'"{name}"'


def _struct(type_name: str, members: List[tuple], doc: str = "") -> str:
    """Render a TYPE ... END_TYPE block. `members` is a list of (name, datatype, comment)."""
    width = max((len(m[0]) for m in members), default=1)
    lines = [HEADER, f"TYPE {_q(type_name)}", "VERSION : 0.1", "   STRUCT"]
    if not members:
        # An empty STRUCT is not valid SCL; keep a documented placeholder member.
        lines.append("      Reserved : Bool;   // no members required by this spec")
    for name, datatype, comment in members:
        pad = " " * (width - len(name))
        suffix = f"   // {comment}" if comment else ""
        lines.append(f"      {name}{pad} : {datatype};{suffix}")
    lines += ["   END_STRUCT;", "", "END_TYPE"]
    if doc:
        lines += ["", "(*", doc.rstrip(), "*)"]
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# UDTs
# --------------------------------------------------------------------------
def auto_members(spec: Spec) -> List[tuple]:
    members = []
    for eq in spec.controlled():
        for suffix, datatype, comment in AUTO_MEMBERS.get(eq.type, []):
            members.append((f"{eq.name}{suffix}", datatype, f"{eq.name}: {comment}"))
    return members


def alarm_members(spec: Spec) -> List[tuple]:
    members: List[tuple] = [("SafetyOpen", "Bool", "safety circuit open (status only)")]
    for eq in spec.controlled():
        roles = eq.typedef.alarm_roles
        if "fault" in roles:
            label = "signal fault / out of range" if eq.type == "analog_input" else "device fault"
            members.append((f"{eq.name}_Fault", "Bool", f"{eq.name}: {label}"))
        if "limits" in roles and _uses_limits(eq):
            sc = eq.scaling
            if sc.get("lo_lo") is not None:
                members.append((f"{eq.name}_LoLo", "Bool", f"{eq.name}: below {sc['lo_lo']} {sc['unit']}"))
            if sc.get("lo") is not None:
                members.append((f"{eq.name}_Lo", "Bool", f"{eq.name}: below {sc['lo']} {sc['unit']}"))
            if sc.get("hi") is not None:
                members.append((f"{eq.name}_Hi", "Bool", f"{eq.name}: above {sc['hi']} {sc['unit']}"))
            if sc.get("hi_hi") is not None:
                members.append((f"{eq.name}_HiHi", "Bool", f"{eq.name}: above {sc['hi_hi']} {sc['unit']}"))
    return members


def cmd_members(spec: Spec) -> List[tuple]:
    return [
        ("Start", "Bool", "momentary: start the auto sequence"),
        ("Stop", "Bool", "momentary: stop the auto sequence"),
        ("Reset", "Bool", "momentary: acknowledge all faults"),
        ("ReqManual", "Bool", "momentary: select manual mode"),
        ("ReqAuto", "Bool", "momentary: select auto mode"),
    ]


def _uses_limits(eq: Equipment) -> bool:
    return any(eq.scaling.get(k) is not None for k in ("lo_lo", "lo", "hi", "hi_hi"))


def emit_udt_auto(spec: Spec) -> str:
    return _struct(
        spec.udt_auto,
        auto_members(spec),
        "Auto-mode requests. The AUTO SEQUENCE region of the machine FB writes these;\n"
        "the device FBs read them. Nothing else should write to this struct.",
    )


def emit_udt_alarms(spec: Spec) -> str:
    return _struct(
        spec.udt_alarms,
        alarm_members(spec),
        "One bit per alarm condition, refreshed every cycle by the machine FB.\n"
        "Bind HMI alarms to <instance DB>.Alarms.<member>.",
    )


def emit_udt_cmd(spec: Spec) -> str:
    return _struct(
        spec.udt_cmd,
        cmd_members(spec),
        "Machine-level HMI commands. All members are momentary: the machine FB\n"
        "evaluates and clears them in the same cycle.",
    )


# --------------------------------------------------------------------------
# Machine FB
# --------------------------------------------------------------------------
def _safety_expression(spec: Spec) -> str:
    inputs = spec.safety_inputs()
    if not inputs:
        return "TRUE"
    terms = []
    for eq in inputs:
        sig = eq.signal("ok_fb")
        terms.append(_q(sig.tag))
    return "\n                    AND ".join(terms)


def _interlock_expression(eq: Equipment) -> str:
    others = eq.options.get("interlock_from") or []
    if not others:
        return "TRUE"
    return " AND ".join(f"#{o}.Hmi.Sts_Running" for o in others)


def _device_call(spec: Spec, eq: Equipment) -> str:
    ctx: Dict = {
        "enable": "#vEnable",
        "manual": "#vManual",
        "reset": "#vReset",
        "auto": "#Auto.",
        "interlock": _interlock_expression(eq),
        "tag": lambda role: _q(eq.signal(role).tag),
        "has": eq.has,
    }
    params = eq.typedef.call(eq, ctx)
    indent = " " * (len(eq.name) + 6)
    body = (",\n" + indent).join(params)
    head = f"    #{eq.name}({body});"
    label = eq.description or eq.typedef.summary
    return f"    // {eq.name}: {label}\n{head}"


def emit_fb_machine(spec: Spec) -> str:
    controlled = spec.controlled()
    lines: List[str] = [HEADER, f"FUNCTION_BLOCK {_q(spec.fb_machine)}"]
    lines.append("{ S7_Optimized_Access := 'TRUE' }")
    lines.append("VERSION : 0.1")

    # ---- interface -------------------------------------------------------
    lines += [
        "   VAR_OUTPUT",
        "      State : Int;                       // see FB_ModeManager states",
        "      AutoRun : Bool;                    // auto sequence is allowed to advance",
        "      AnyFault : Bool;                   // at least one alarm is active",
        "   END_VAR",
        "",
        "   VAR",
        f"      Mode : {_q('FB_ModeManager')};",
        f"      Cmd : {_q(spec.udt_cmd)};              // HMI machine commands",
        f"      Auto : {_q(spec.udt_auto)};            // auto-mode requests",
        f"      Alarms : {_q(spec.udt_alarms)};        // alarm bits for the HMI",
        "      DevicesHealthy : Bool := TRUE;     // aggregated at the end of each cycle",
    ]
    if spec.sequence:
        lines += [
            f"      Cond : {_q(spec.udt_cond)};            // resolved step conditions",
            f"      Seq : {_q(spec.fb_sequence)};          // the generated step sequence",
        ]
    if controlled:
        lines.append("      // ---- device instances ----")
        width = max(len(e.name) for e in controlled)
        for eq in controlled:
            pad = " " * (width - len(eq.name))
            lines.append(f"      {eq.name}{pad} : {_q(eq.typedef.fb)};")
    lines += [
        "   END_VAR",
        "",
        "   VAR_TEMP",
        "      vSafetyOk : Bool;",
        "      vEnable : Bool;",
        "      vManual : Bool;",
        "      vReset : Bool;",
        "   END_VAR",
        "",
        "BEGIN",
    ]

    # ---- 1. safety status ------------------------------------------------
    lines += [
        "    // ==================================================================",
        "    // 1. Safety STATUS aggregation.",
        "    //    These contacts tell the standard program what the safety system",
        "    //    is doing. They do not implement the safety function itself.",
        "    // ==================================================================",
        f"    #vSafetyOk := {_safety_expression(spec)};",
        "",
    ]

    # ---- 2. mode manager -------------------------------------------------
    start_eq = spec.by_control_role("start")
    stop_eq = spec.by_control_role("stop")
    reset_eq = spec.by_control_role("reset")

    start_expr = "#Cmd.Start"
    if start_eq:
        start_expr = f"#Cmd.Start OR {_q(start_eq.signal('in').tag)}"
    stop_expr = "TRUE"
    if stop_eq:
        stop_expr = _q(stop_eq.signal("in").tag)
    reset_expr = "#Cmd.Reset"
    if reset_eq:
        reset_expr = f"#Cmd.Reset OR {_q(reset_eq.signal('in').tag)}"

    lines += [
        "    // ==================================================================",
        "    // 2. Mode manager. Owns Enable, the manual/auto selection and reset.",
        "    // ==================================================================",
        "    #Mode(SafetyOk := #vSafetyOk,",
        "          DevicesHealthy := #DevicesHealthy,",
        "          ReqManual := #Cmd.ReqManual,",
        "          ReqAuto := #Cmd.ReqAuto,",
        f"          StartCmd := {start_expr},",
        "          StopCmd := #Cmd.Stop,",
        f"          StopOk := {stop_expr},",
        f"          ResetCmd := {reset_expr},",
    ]
    if spec.sequence:
        # The sequencer runs later in this cycle, so this is last cycle's pulse.
        # One cycle late to leave auto is harmless, and it avoids reordering the
        # mode manager behind the sequence it gates.
        lines.append("          CycleComplete := #Seq.Complete);")
    else:
        lines.append("          CycleComplete := FALSE);")
    lines += [
        "",
        "    // Momentary HMI commands are consumed once the mode manager has seen them.",
        "    #Cmd.Start := FALSE;",
        "    #Cmd.Stop := FALSE;",
        "    #Cmd.Reset := FALSE;",
        "    #Cmd.ReqManual := FALSE;",
        "    #Cmd.ReqAuto := FALSE;",
        "",
        "    #vEnable := #Mode.Enable;",
        "    #vManual := #Mode.ManualMode;",
        "    #vReset := #Mode.GroupReset;",
        "    #State := #Mode.State;",
        "    #AutoRun := #Mode.AutoRun;",
        "",
    ]

    # ---- 3. auto sequence region ----------------------------------------
    if spec.sequence:
        lines += [
            "    // ==================================================================",
            "    // 3. AUTO SEQUENCE - generated from the spec's sequence section.",
            "    //",
            "    //    The step logic lives in its own FB. Edit the spec and rebuild;",
            "    //    the hand-written region below is for anything the step table",
            "    //    cannot express, and runs after the sequencer each cycle.",
            "    // ==================================================================",
            "    IF NOT #AutoRun THEN",
        ]
    else:
        lines += [
            "    // ==================================================================",
            "    // 3. AUTO SEQUENCE - machine specific, written by hand.",
            "    //",
            "    //    Everything above and below this region is generated. Write the",
            "    //    sequence here by setting members of #Auto, gated on #AutoRun.",
            "    //    Regenerating the project preserves nothing inside this region,",
            "    //    so keep the sequence in its own block once it grows: create an",
            "    //    FB, add it to the spec as a library block and call it from here.",
            "    // ==================================================================",
            "    IF NOT #AutoRun THEN",
        ]
    lines += [
        "        // Auto is not running: drop every auto request so manual mode is clean.",
    ]
    for name, datatype, _ in auto_members(spec):
        default = "0.0" if datatype == "Real" else "FALSE"
        lines.append(f"        #Auto.{name} := {default};")
    if not auto_members(spec):
        lines.append("        ;   // no auto requests in this spec")
    lines += ["    END_IF;", ""]
    if spec.sequence:
        from . import emit_seq
        lines += emit_seq.machine_call(spec, spec.sequence)
        lines += [
            "    // >>> BEGIN AUTO SEQUENCE >>>",
            "    // The step table above owns the sequence. Use this region only for",
            "    // what a step table cannot say - it runs after the sequencer, so an",
            "    // assignment here overrides the active step's request.",
            "    ;",
            "    // <<< END AUTO SEQUENCE <<<",
            "",
        ]
    else:
        lines += ["    // >>> BEGIN AUTO SEQUENCE >>>"]
        lines += _sequence_hint(spec)
        lines += ["    // <<< END AUTO SEQUENCE <<<", ""]

    # ---- 4. device calls -------------------------------------------------
    lines += [
        "    // ==================================================================",
        "    // 4. Device calls. One call per piece of equipment in the spec.",
        "    // ==================================================================",
    ]
    if controlled:
        for eq in controlled:
            lines.append(_device_call(spec, eq))
            lines.append("")
    else:
        lines += ["    ;   // no controlled equipment in this spec", ""]

    # ---- 5. alarms -------------------------------------------------------
    lines += [
        "    // ==================================================================",
        "    // 5. Alarm bits and health aggregation.",
        "    // ==================================================================",
        "    #Alarms.SafetyOpen := NOT #vSafetyOk;",
    ]
    fault_terms: List[str] = ["#Alarms.SafetyOpen"]
    for eq in spec.controlled():
        roles = eq.typedef.alarm_roles
        if "fault" in roles:
            lines.append(f"    #Alarms.{eq.name}_Fault := #{eq.name}.Fault;")
            fault_terms.append(f"#Alarms.{eq.name}_Fault")
        if "limits" in roles and _uses_limits(eq):
            sc = eq.scaling
            if sc.get("lo_lo") is not None:
                lines.append(f"    #Alarms.{eq.name}_LoLo := #{eq.name}.AlmLoLo;")
                fault_terms.append(f"#Alarms.{eq.name}_LoLo")
            if sc.get("lo") is not None:
                lines.append(f"    #Alarms.{eq.name}_Lo := #{eq.name}.AlmLo;")
            if sc.get("hi") is not None:
                lines.append(f"    #Alarms.{eq.name}_Hi := #{eq.name}.AlmHi;")
            if sc.get("hi_hi") is not None:
                lines.append(f"    #Alarms.{eq.name}_HiHi := #{eq.name}.AlmHiHi;")
                fault_terms.append(f"#Alarms.{eq.name}_HiHi")

    lines.append("")
    lines.append("    // Only latching / trip-level conditions block the machine.")
    if len(fault_terms) == 1:
        lines.append(f"    #AnyFault := {fault_terms[0]};")
    else:
        joined = "\n                ".join(
            [fault_terms[0]] + [f"OR {t}" for t in fault_terms[1:]]
        )
        lines.append(f"    #AnyFault := {joined};")
    lines += [
        "    #DevicesHealthy := NOT #AnyFault;",
        "END_FUNCTION_BLOCK",
    ]
    return "\n".join(lines) + "\n"


def _sequence_hint(spec: Spec) -> List[str]:
    """A commented, spec-specific example of the sequence idiom."""
    motors = [e for e in spec.controlled() if e.type in ("motor_dol", "motor_reversing", "vfd_analog")]
    valves = [e for e in spec.controlled() if e.type in ("valve_single", "valve_double")]
    sensors = [e for e in spec.equipment if e.type == "digital_input"
               and not e.options.get("control_role")]

    if not motors:
        return ["", "    // Write the auto-mode logic here, gated on #AutoRun.", ""]

    motor = motors[0]
    lines = [
        "",
        "    // The idiom: gate everything on #AutoRun and write only to #Auto members.",
        "    // Device FBs own the outputs - never write a %Q tag from here.",
        "    //",
        "    // IF #AutoRun THEN",
        f"    //     #Auto.{motor.name}_Start := TRUE;",
    ]
    if valves:
        condition = f"#{motor.name}.Hmi.Sts_Running"
        if sensors:
            condition = f'"{sensors[0].name}" AND {condition}'
        lines.append(f"    //     #Auto.{valves[0].name}_Open := {condition};")
    if motor.type == "vfd_analog":
        lines.append(f"    //     #Auto.{motor.name}_Speed := 35.0;")
    lines += [
        "    // ELSE",
        f"    //     #Auto.{motor.name}_Stop := TRUE;",
        "    // END_IF;",
        "",
    ]
    return lines


# --------------------------------------------------------------------------
# OB
# --------------------------------------------------------------------------
def emit_ob_main(spec: Spec) -> str:
    return (
        HEADER
        + f"ORGANIZATION_BLOCK {_q(spec.ob_main)}\n"
        "TITLE = 'Program cycle'\n"
        "{ S7_Optimized_Access := 'TRUE' }\n"
        "VERSION : 0.1\n"
        "BEGIN\n"
        f"    {_q(spec.db_machine)}();\n"
        "END_ORGANIZATION_BLOCK\n"
        "\n"
        "(*\n"
        f"   Calls the machine FB through its instance DB {spec.db_machine}.\n"
        "\n"
        "   The build plan deletes the project's default Main [OB1] before importing\n"
        "   this one, so that OB1 ends up as this SCL block. If your TIA version\n"
        "   refuses the import, keep the original Main [OB1] and add the single line\n"
        f"   {spec.db_machine}(); to it by hand - that is the only manual code step.\n"
        "*)\n"
    )
