"""Rule implementations for `tiagen lint`.

Each is `check_<name>(project, rule) -> list[Finding]`, matching the `name` field in
`rules.yaml`. The engine finds them by name, so adding a rule is one YAML entry and
one function here.

Rules needing network structure test `block.structured` first. A block read as text
only must be reported as unchecked, never as clean - see `lint.format_report`.
"""

from __future__ import annotations

import os
import re
from collections import defaultdict
from typing import Dict, List, Optional

from . import devices as dev
from .lint import Block, Finding, Project, Rule, Severity, SourceFile

# A bypass is a bypass in any notation, but the word has to be found in the right
# place. Two very different signals get conflated if you just grep the file:
#
#   an IDENTIFIER containing one of these    -> a real leftover bit
#   the word appearing in prose              -> usually documentation
#
# "// an assignment here overrides the active step's request" is a comment doing its
# job; VAR_TEMP is a language keyword. Neither is a bypass, and reporting them
# teaches people to ignore the rule - which costs more than the rule is worth.
_DEBUG_IDENT_WORDS = (
    "bypass", "debug", "dummy", "testbit", "forcebit", "tempbit", "scrap",
    "temp", "tmp", "force",
)
_DEBUG_IDENT_RE = re.compile("|".join(re.escape(w) for w in _DEBUG_IDENT_WORDS), re.I)
# In comments, only an explicit unfinished-work marker counts.
_MARKER_RE = re.compile(r"\b(TODO|FIXME|HACK|XXX|WORKAROUND)\b", re.I)
_IDENTIFIER_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")

# SCL keywords and standard identifiers that contain a flagged word by coincidence.
_KEYWORD_ALLOWLIST = {
    "var_temp", "temp", "var", "var_input", "var_output", "var_in_out", "var_global",
    "end_var", "tempo", "template",
    # Generated and library members whose names describe a real feature.
    "sts_simulated", "usesimulation", "simulate", "forcemode",
}

_GENERATED_MARKER = "Generated by tiagen"
_SEQUENCE_REGION = ("BEGIN AUTO SEQUENCE", "END AUTO SEQUENCE")

# %Q0.0, %QW64, %QX1.2 - a physical output write.
_OUTPUT_WRITE = re.compile(r'(?P<addr>%Q[WBDX]?\d+(?:\.\d+)?)\s*:=')
_ABSOLUTE_ADDR = re.compile(r"%[IQM][WBDX]?\d+(?:\.\d+)?")
# Clock and system memory bytes live in M. A write to them from the program is the
# S7 equivalent of writing a Panasonic special relay.
_MEMORY_WRITE = re.compile(r'(?P<addr>%M[WBDX]?\d+(?:\.\d+)?)\s*:=')
_ALWAYS_TRUE = re.compile(r"\bIF\s+TRUE\s+THEN\b|\bAND\s+TRUE\b|:=\s*TRUE\s*;\s*//\s*force", re.I)


def _finding(rule: Rule, message: str, **kwargs) -> Finding:
    return Finding(
        rule_id=rule.id, rule_name=rule.name, severity=rule.severity,
        message=message, **kwargs,
    )


def _library_sources(project: Project) -> Dict[str, str]:
    """Every library block's canonical text, by block name."""
    if not project.library_dir or not os.path.isdir(project.library_dir):
        return {}
    from . import lint_parse

    canonical: Dict[str, str] = {}
    for name in dev.LIBRARY_FILES:
        path = os.path.join(project.library_dir, name)
        if not os.path.exists(path):
            continue
        for block in lint_parse.parse_scl(lint_parse._read_text(path)):
            canonical[block.name] = block.text
    return canonical


def _normalise(text: str) -> str:
    """Compare logic, not layout.

    Whitespace and comments are stripped so that reformatting a library block, or
    translating its comments, is not reported as a functional change. What remains
    is the code - if that differs, somebody changed behaviour.
    """
    without_block_comments = re.sub(r"\(\*.*?\*\)", "", text, flags=re.S)
    lines = []
    for line in without_block_comments.splitlines():
        line = re.sub(r"//.*$", "", line)
        line = " ".join(line.split())
        if line:
            lines.append(line)
    return "\n".join(lines).upper()


# --------------------------------------------------------------------------
# L001 / L002 - integrity
# --------------------------------------------------------------------------
def check_library_block_modified(project: Project, rule: Rule) -> List[Finding]:
    canonical = _library_sources(project)
    if not canonical:
        return []

    findings = []
    for block in project.blocks:
        reference = canonical.get(block.name)
        if reference is None or not block.text:
            continue
        if _normalise(block.text) != _normalise(reference):
            source = project.file_of(block)
            findings.append(_finding(
                rule,
                f"'{block.name}' differs from the reviewed library block. Comments and "
                "formatting are ignored in this comparison, so the logic itself has "
                "changed. Fix the library and regenerate, or rename the block so it is "
                "visibly bespoke.",
                path=source.path if source else "",
                line=block.start_line,
                block=block.name,
            ))
    return findings


def check_generated_block_edited(project: Project, rule: Rule) -> List[Finding]:
    findings = []
    for source in project.files:
        if _GENERATED_MARKER not in source.text:
            continue
        # The sanctioned exception: whatever sits between the AUTO SEQUENCE markers.
        # Everything else in a generated file is overwritten on the next build.
        outside = _text_outside_sequence_region(source.text)
        edited = _looks_hand_edited(outside)
        if edited:
            findings.append(_finding(
                rule,
                f"carries the generated header but {edited}. The next build overwrites "
                "this. Move the change into the spec, or into the AUTO SEQUENCE region.",
                path=source.path,
            ))
    return findings


def _text_outside_sequence_region(text: str) -> str:
    begin, end = _SEQUENCE_REGION
    lines = text.splitlines()
    keep, inside = [], False
    for line in lines:
        if begin in line:
            inside = True
            continue
        if end in line:
            inside = False
            continue
        if not inside:
            keep.append(line)
    return "\n".join(keep)


def _looks_hand_edited(text: str) -> Optional[str]:
    """Signs of a hand edit in generated text.

    Conservative on purpose: this rule accusing somebody wrongly is worse than it
    missing a case, because the fix it demands is to move work into the spec.
    """
    markers = [
        (re.compile(r"//\s*(TODO|FIXME|HACK|XXX)\b", re.I), "contains a TODO or FIXME"),
        (re.compile(r"//\s*(added|changed|modified|patched|edited)\b", re.I),
         "contains a comment saying it was changed by hand"),
        (re.compile(r"//\s*DO NOT (REGENERATE|REBUILD|OVERWRITE)", re.I),
         "asks not to be regenerated"),
    ]
    for pattern, description in markers:
        if pattern.search(text):
            return description
    return None


# --------------------------------------------------------------------------
# L003 / L004 - commissioning leftovers
# --------------------------------------------------------------------------
def check_test_bypass_bit(project: Project, rule: Rule) -> List[Finding]:
    findings = []
    seen = set()
    for source in project.files:
        for number, line in enumerate(source.lines, start=1):
            code, _, comment = line.partition("//")

            for identifier in _IDENTIFIER_RE.findall(code):
                if identifier.lower() in _KEYWORD_ALLOWLIST:
                    continue
                if not _DEBUG_IDENT_RE.search(identifier):
                    continue
                key = (source.path, identifier.lower())
                if key in seen:
                    continue
                seen.add(key)
                findings.append(_finding(
                    rule,
                    f"'{identifier}' reads like a test or bypass bit left from "
                    "commissioning. Confirm it is gone before this machine ships.",
                    path=source.path,
                    line=number,
                ))

            marker = _MARKER_RE.search(comment)
            if marker:
                key = (source.path, comment.strip()[:60])
                if key in seen:
                    continue
                seen.add(key)
                findings.append(_finding(
                    rule,
                    f"unfinished work marked here: {comment.strip()[:110]}",
                    path=source.path,
                    line=number,
                ))
    return findings


def check_forced_true_condition(project: Project, rule: Rule) -> List[Finding]:
    findings = []
    for source in project.files:
        for number, line in enumerate(source.lines, start=1):
            if _ALWAYS_TRUE.search(line):
                findings.append(_finding(
                    rule,
                    f"this condition is unconditional: {line.strip()[:110]}",
                    path=source.path,
                    line=number,
                ))
    return findings


# --------------------------------------------------------------------------
# L005 / L006 - output ownership
# --------------------------------------------------------------------------
def check_duplicate_output_write(project: Project, rule: Rule) -> List[Finding]:
    findings = []
    for block in project.blocks:
        if not block.text:
            continue
        writes: Dict[str, List[int]] = defaultdict(list)
        for offset, line in enumerate(block.text.splitlines()):
            stripped = re.sub(r"//.*$", "", line)
            for match in _OUTPUT_WRITE.finditer(stripped):
                writes[match.group("addr")].append(block.start_line + offset)
        source = project.file_of(block)
        for address, lines in sorted(writes.items()):
            if len(lines) > 1:
                findings.append(_finding(
                    rule,
                    f"{address} is written on lines {', '.join(str(n) for n in lines)} of "
                    f"'{block.name}'. Only the last write survives the scan.",
                    path=source.path if source else "",
                    line=lines[0],
                    block=block.name,
                ))
    return findings


def check_output_written_outside_device_fb(project: Project, rule: Rule) -> List[Finding]:
    library_names = set(_library_sources(project))
    findings = []
    for block in project.blocks:
        if not block.text or block.name in library_names:
            continue
        source = project.file_of(block)
        for offset, line in enumerate(block.text.splitlines()):
            stripped = re.sub(r"//.*$", "", line)
            match = _OUTPUT_WRITE.search(stripped)
            if match:
                findings.append(_finding(
                    rule,
                    f"'{block.name}' writes {match.group('addr')} directly. The house "
                    "pattern is that a device FB owns each output, so there is one place "
                    "to look when it misbehaves.",
                    path=source.path if source else "",
                    line=block.start_line + offset,
                    block=block.name,
                ))
    return findings


# --------------------------------------------------------------------------
# L007 / L008 - addressing
# --------------------------------------------------------------------------
def check_absolute_address_used(project: Project, rule: Rule) -> List[Finding]:
    findings = []
    seen = set()
    for block in project.blocks:
        if not block.text:
            continue
        source = project.file_of(block)
        for offset, line in enumerate(block.text.splitlines()):
            stripped = re.sub(r"//.*$", "", line)
            for match in _ABSOLUTE_ADDR.finditer(stripped):
                key = (block.name, match.group(0))
                if key in seen:
                    continue
                seen.add(key)
                findings.append(_finding(
                    rule,
                    f"'{block.name}' refers to {match.group(0)} absolutely. A symbol "
                    "survives a rewire; an address does not.",
                    path=source.path if source else "",
                    line=block.start_line + offset,
                    block=block.name,
                ))
    return findings


def check_system_memory_write(project: Project, rule: Rule) -> List[Finding]:
    findings = []
    for block in project.blocks:
        if not block.text:
            continue
        source = project.file_of(block)
        for offset, line in enumerate(block.text.splitlines()):
            stripped = re.sub(r"//.*$", "", line)
            match = _MEMORY_WRITE.search(stripped)
            if match:
                findings.append(_finding(
                    rule,
                    f"'{block.name}' writes {match.group('addr')}. If that is the CPU's "
                    "clock or system memory byte it is read-only to the program; if it is "
                    "a flag, give it a symbol.",
                    path=source.path if source else "",
                    line=block.start_line + offset,
                    block=block.name,
                ))
    return findings


# --------------------------------------------------------------------------
# L009 / L010 / L012 - documentation
# --------------------------------------------------------------------------
def check_block_missing_comment(project: Project, rule: Rule) -> List[Finding]:
    findings = []
    for block in project.blocks:
        if block.title.strip() or block.comment.strip():
            continue
        source = project.file_of(block)
        findings.append(_finding(
            rule,
            f"'{block.name}' has no title or description.",
            path=source.path if source else "",
            line=block.start_line,
            block=block.name,
        ))
    return findings


def check_network_missing_comment(project: Project, rule: Rule) -> List[Finding]:
    findings = []
    for block in project.structured_blocks:
        source = project.file_of(block)
        for network in block.networks:
            if network.has_comment:
                continue
            findings.append(_finding(
                rule,
                f"network {network.number} of '{block.name}' has no comment.",
                path=source.path if source else "",
                line=network.start_line,
                block=block.name,
            ))
    return findings


def check_duplicate_comment(project: Project, rule: Rule) -> List[Finding]:
    findings = []
    for block in project.structured_blocks:
        by_text: Dict[str, List[int]] = defaultdict(list)
        for network in block.networks:
            text = " ".join((network.title + " " + network.comment).split()).lower()
            if text:
                by_text[text].append(network.number)
        source = project.file_of(block)
        for text, numbers in by_text.items():
            if len(numbers) > 1:
                findings.append(_finding(
                    rule,
                    f"networks {', '.join(str(n) for n in numbers)} of '{block.name}' "
                    f"share the comment '{text[:70]}'. One was probably copied.",
                    path=source.path if source else "",
                    block=block.name,
                ))
    return findings
